import { defineStore } from "pinia";

const productsDetails = defineStore("storedProducts", {
  state: () => ({
    storedProducts: [
      {
        id: "Waffle",
        title: "Waffle",
        details: "Waffle with Berries",
        price: 6.5,
        mob: require("@/assets/images/image-waffle-mobile.jpg"),
        desk: require("@/assets/images/image-waffle-desktop.jpg"),
        tab: require("@/assets/images/image-waffle-tablet.jpg"),
        thum: require("@/assets/images/image-waffle-thumbnail.jpg"),
      },
      {
        id: "Crème",
        title: "Crème Brûlée",
        details: "Vanilla Bean Crème Brûlée",
        price: 7.0,
        mob: require("@/assets/images/image-creme-brulee-mobile.jpg"),
        desk: require("@/assets/images/image-creme-brulee-desktop.jpg"),
        tab: require("@/assets/images/image-creme-brulee-tablet.jpg"),
        thum: require("@/assets/images/image-creme-brulee-thumbnail.jpg"),
      },
      {
        id: "Macaron",
        title: "Macaron",
        details: "Macaron Mix of Five",
        price: 8.0,
        mob: require("@/assets/images/image-macaron-mobile.jpg"),
        desk: require("@/assets/images/image-macaron-desktop.jpg"),
        tab: require("@/assets/images/image-macaron-tablet.jpg"),
        thum: require("@/assets/images/image-macaron-thumbnail.jpg"),
      },
      {
        id: "Tiramisu",
        title: "Tiramisu",
        details: "Classic Tiramisu",
        price: 5.5,
        mob: require("@/assets/images/image-tiramisu-mobile.jpg"),
        desk: require("@/assets/images/image-tiramisu-desktop.jpg"),
        tab: require("@/assets/images/image-tiramisu-tablet.jpg"),
        thum: require("@/assets/images/image-tiramisu-thumbnail.jpg"),
      },
      {
        id: "Baklava",
        title: "Baklava",
        details: "Pistachio Baklava",
        price: 4.0,
        mob: require("@/assets/images/image-baklava-mobile.jpg"),
        desk: require("@/assets/images/image-baklava-desktop.jpg"),
        tab: require("@/assets/images/image-baklava-tablet.jpg"),
        thum: require("@/assets/images/image-baklava-thumbnail.jpg"),
      },
      {
        id: "Pie",
        title: "Pie",
        details: "Lemon Meringue Pie",
        price: 5.0,
        mob: require("@/assets/images/image-meringue-mobile.jpg"),
        desk: require("@/assets/images/image-meringue-desktop.jpg"),
        tab: require("@/assets/images/image-meringue-tablet.jpg"),
        thum: require("@/assets/images/image-meringue-thumbnail.jpg"),
      },
      {
        id: "Cake",
        title: "Cake",
        details: "Red Velvet Cake",
        price: 4.5,
        mob: require("@/assets/images/image-cake-mobile.jpg"),
        desk: require("@/assets/images/image-cake-desktop.jpg"),
        tab: require("@/assets/images/image-cake-tablet.jpg"),
        thum: require("@/assets/images/image-cake-thumbnail.jpg"),
      },
      {
        id: "Brownie",
        title: "Brownie",
        details: "Salted Caramel Brownie",
        price: 4.5,
        mob: require("@/assets/images/image-brownie-mobile.jpg"),
        desk: require("@/assets/images/image-brownie-desktop.jpg"),
        tab: require("@/assets/images/image-brownie-tablet.jpg"),
        thum: require("@/assets/images/image-brownie-thumbnail.jpg"),
      },
      {
        id: "Panna",
        title: "Panna Cotta",
        details: "Vanilla Panna Cotta",
        price: 6.5,
        mob: require("@/assets/images/image-panna-cotta-mobile.jpg"),
        desk: require("@/assets/images/image-panna-cotta-desktop.jpg"),
        tab: require("@/assets/images/image-panna-cotta-tablet.jpg"),
        thum: require("@/assets/images/image-panna-cotta-thumbnail.jpg"),
      },
    ],
  }),
});

export default productsDetails;
